---
- name: Create installation directory
  file:
    path: '{{ prometheus_path }}'
    state: directory
    owner: root
    group: root
    mode: 0775
- name: Copy docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: '{{ prometheus_path }}/docker-compose.yml'
    owner: root
    group: root
    mode: 0664
- name: Copy prometheus.yml
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: '{{ prometheus_path }}/prometheus.yml'
    owner: root
    group: root
    mode: 0664
- name: Copy alertrules.yml
  ansible.builtin.copy:
    src: alertrules.yml
    dest: '{{ prometheus_path }}/alertrules.yml'
    owner: root
    group: root
    mode: 0664
- name: Copy scrape_configs.yml
  ansible.builtin.copy:
    src: scrape_configs.yml
    dest: '{{ prometheus_path }}/scrape_configs.yml'
    owner: root
    group: root
    mode: 0664
- name: Copy prometheus_sonnen.yml
  ansible.builtin.template:
    src: prometheus.yml.j2
    dest: '{{ prometheus_path }}/prometheus_sonnen.yml'
    owner: root
    group: root
    mode: 0664
- name: Copy alertrules_sonnen.yml
  ansible.builtin.copy:
    src: alertrules_sonnen.yml
    dest: '{{ prometheus_path }}/alertrules_sonnen.yml'
    owner: root
    group: root
    mode: 0664
- name: Copy scrape_configs_sonnen.yml
  ansible.builtin.copy:
    src: scrape_configs_sonnen.yml
    dest: '{{ prometheus_path }}/scrape_configs_sonnen.yml'
    owner: root
    group: root
    mode: 0664
- name: Enable daily upgrade of base image
  ansible.builtin.cron:
    name: 'Upgrade {{ prometheus_path }}'
    user: root
    hour: 4
    minute: 0
    job: 'docker compose -f {{ prometheus_path }}/docker-compose.yml down && docker compose -f {{ prometheus_path }}/docker-compose.yml pull && docker compose -f {{ prometheus_path }}/docker-compose.yml up -d'
- name: Copy backup_prometheus.sh
  ansible.builtin.template:
    src: backup_prometheus.sh.j2
    dest: '{{ prometheus_path }}/backup_prometheus.sh'
    owner: root
    group: root
    mode: 0775
- name: Enable daily backup
  ansible.builtin.cron:
    name: 'Backup {{ prometheus_path }} daily'
    user: root
    hour: 1
    minute: 0
    job: '{{ prometheus_path }}/backup_prometheus.sh'
- name: Enable weekly backup
  ansible.builtin.cron:
    name: 'Backup {{ prometheus_path }} weekly'
    user: root
    weekday: 0
    hour: 1
    minute: 0
    job: '{{ prometheus_path }}/backup_prometheus.sh weekly'
- name: Enable monthly backup
  ansible.builtin.cron:
    name: 'Backup {{ prometheus_path }} monthly'
    user: root
    day: 1
    hour: 1
    minute: 0
    job: '{{ prometheus_path }}/backup_prometheus.sh monthly'
