---
- name: Create installation directory
  file:
    path: '{{ prometheus_path }}'
    state: directory
    owner: root
    group: root
    mode: 0775
- name: Copy docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: '{{ prometheus_path }}/docker-compose.yml'
    owner: root
    group: root
    mode: 0664
- name: Copy prometheus.yml
  ansible.builtin.copy:
    src: prometheus.yml
    dest: '{{ prometheus_path }}/prometheus.yml'
    owner: root
    group: root
    mode: 0664
- name: Enable daily upgrade of base image
  ansible.builtin.cron:
    name: 'Upgrade {{ prometheus_path }}'
    user: root
    hour: 4
    minute: 0
    job: 'docker compose -f {{ prometheus_path }}/docker-compose.yml down && docker compose -f {{ prometheus_path }}/docker-compose.yml pull && docker compose -f {{ prometheus_path }}/docker-compose.yml up -d'
- name: Copy backup_prometheus.sh
  ansible.builtin.template:
    src: backup_prometheus.sh.j2
    dest: '{{ prometheus_path }}/backup_prometheus.sh'
    owner: root
    group: root
    mode: 0774
- name: Enable daily backup
  ansible.builtin.cron:
    name: 'Backup {{ prometheus_path }}'
    user: root
    hour: 3
    minute: 0
    job: '{{ prometheus_path }}/backup_prometheus.sh'
