---
- name: Create installation directory
  ansible.builtin.file:
    path: '{{ prometheus_alertmanager.path }}'
    state: directory
    owner: root
    group: root
    mode: '0775'
- name: Copy docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: '{{ prometheus_alertmanager.path }}/docker-compose.yml'
    owner: root
    group: root
    mode: '0664'
- name: Copy alertmanager.yml
  ansible.builtin.template:
    src: alertmanager.yml.j2
    dest: '{{ prometheus_alertmanager.path }}/alertmanager.yml'
    owner: root
    group: root
    mode: '0664'
- name: Enable daily upgrade of base image
  ansible.builtin.cron:
    name: 'Upgrade {{ prometheus_alertmanager.path }}'
    user: root
    hour: '{{ prometheus_alertmanager.update_docker.time.cron_hour }}'
    minute: '{{ prometheus_alertmanager.update_docker.time.cron_minute }}'
    job: >
      docker compose -f {{ prometheus_alertmanager.path }}/docker-compose.yml stop &&
      docker compose -f {{ prometheus_alertmanager.path }}/docker-compose.yml pull &&
      docker compose -f {{ prometheus_alertmanager.path }}/docker-compose.yml up -d
