---
- name: Create installation directory
  file:
    path: '{{ snmp_exporter_path }}'
    state: directory
    owner: root
    group: root
    mode: 0775
- name: Copy docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: '{{ snmp_exporter_path }}/docker-compose.yml'
    owner: root
    group: root
    mode: 0664
- name: Copy snmp.yml
  ansible.builtin.copy:
    src: snmp.yml
    dest: '{{ snmp_exporter_path }}/snmp.yml'
    owner: root
    group: root
    mode: 0664
- name: Enable daily upgrade of base image
  ansible.builtin.cron:
    name: 'Upgrade {{ snmp_exporter_path }}'
    user: root
    hour: 4
    minute: 0
    job: 'docker compose -f {{ snmp_exporter_path }}/docker-compose.yml down && docker compose -f {{ snmp_exporter_path }}/docker-compose.yml pull && docker compose -f {{ snmp_exporter_path }}/docker-compose.yml up -d'
