- name: Install Prometheus
  hosts: prometheus
  become: true
  roles:
    - install-prometheus
- name: Install Prometheus Sonnen
  hosts: prometheus_sonnen
  become: true
  roles:
    - install-prometheus-sonnen
- name: Install Prometheus Alertmanager
  hosts: prometheus_alertmanager
  become: true
  roles:
    - install-prometheus-alertmanager
- name: Install Node exporter
  hosts: prometheus_node_exporter
  become: true
  roles:
    - prometheus.prometheus.node_exporter
  vars:
    node_exporter_enabled_collectors: ["systemd", "processes", {"textfile": {"directory": "{{ node_exporter_textfile_dir }}"}}]
- name: Install SNMP exporter
  hosts: prometheus_snmp_exporter
  become: true
  roles:
    - install-snmp_exporter
