scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - YOURPROMETHEUSURL:9090
    - YOURPROMETHEUSURL:9091
- job_name: node
  honor_timestamps: true
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - NODETARGET1URL:9100
    - NODETARGET2URL:9100
- job_name: 'snmp-exporter'
  static_configs:
  - targets:
    - SNMPTARGET1URL
    - SNMPTARGET2URL
  metrics_path: /snmp
  params:
    module: [synology]
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - source_labels: [__param_target]
      regex: (.*)
      replacement: YOURSNMPEXPORTERURL:9116
      target_label: __address__
